### ISSUE TITLE
PointToPoint constructor given wrong information -> NullPointerException

### ISSUE THREAD

**Issue by paaff** [michele-loreti/jResp#1]
Hello!
It seems that a bug can be provoked by  the following behavior.

If a *PointToPoint* object is initialized with a name of a *Node* that does not exist, the program will not compile and return a *NullPointerException*, instead of a relaying a more useful message to the user :)

I have a sample program that will provoke the bug:
[PointToPointConstructorExample.zip](https://github.com/michele-loreti/jResp/files/686829/PointToPointConstructorExample.zip)

In line 43 and 45, the *PointToPoint* object is initialized with wrong *Node* names, thus provoking the bug. Changing the names to **Node1** and **Node2** respectively, the exception will not be raised.

Regarding the jResp code, I have only taken a brief look at it and have not found the correct explanation or solution, but it seems that in the method  *sendPutRequest*  in  *Node.java*, the call:

      return pending.get();

at https://github.com/michele-loreti/jResp/blob/master/CORE/org.cmg.jresp.core/src/org/cmg/jresp/comp/Node.java#L1063

returns a null value for some reason.

Thanks :)

**Comment by michele-loreti** [comment]
We have fixed this bug! Note that you can check if a 'put' succeeds or not by verifying if the returned value is true or false.
